### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by wgliang** [ohmq/ohmyqueue#1]
1.一个系统尤其是分布式系统，我觉得一个重要点是日志，日志，日志

2.package分的太碎，建议合并非核心package，或者说ohmyqueue根本不需要分package啦

3.单元测试，单元测试

4。代码规范建议用https://github.com/wgliang/gometalinter下面的工具跑一下相信你会有收获的

加油！！

**Comment by skywalkerlee** [comment]
good suggestion

**Comment by skywalkerlee** [comment]
@wgliang good suggestion
